# =============================================================================
# Modeling_Tool.Feature.Distribution_Tool
# -----------------------------------------------------------------------------
# Copyright (c) 2026 Kyle Sun <github.com/Kyle-J-Sun>. All rights reserved.
# SuperModelingFactory — Licensed under the Business Source License 1.1.
#
# This stub describes the public API of a closed-source module compiled to a
# native extension (.so / .pyd). The original source is not distributed.
# Production / commercial use requires a separate commercial license.
#
# FINGERPRINT: SMF-DISTRIBUTION-eba574de
#   (Unique trace marker. Do not remove or alter — used for plagiarism
#    detection across the public internet.)
# =============================================================================

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

class proc_means:
    def __init__(self, data, varlist, groupby, spec_missing_value = None): ...
    def treat_spec_missing(self): ...
    def group_means(self, q = None): ...
    def group_sum(self): ...
    def __call__(self, q = None): ...
def proc_means_by_grp(data, varlist, groupby = None, spec_missing_value = None, q = None): ...

class DistributionShiftAnalyzer:
    def __init__(self, data, grp_name, benchmark_value): ...
    def analyze_single_var(self, var, outlier_value = 0.99): ...
    def analyze(self, varlist, outlier_value = 0.99): ...
def get_distribution_shift_single_var(data, var, grp_name, benchmark_value, outlier_value = 0.99): ...
def get_distribution_shift(data, varlist, grp_name, benchmark_value, outlier_value = 0.99): ...

class DistributionPlotter:
    def __init__(self, data, score): ...
    def plot_rugplot(self, figsize = (15, 15), title = 'Distribution Plot'): ...
    def plot_kdeplot(self, figsize = (15, 15), title = 'Distribution Plot'): ...
    def plot_displot(self, figsize = (15, 15), title = 'Distribution Plot', nbins = 10): ...
    def plot(self, method = 'displot', title = 'Distribution Plot', figsize = (15, 15), nbins = 10): ...
def plot_distribution(data, score, method = 'displot', title = 'Distribution Plot', figsize = (15, 15), nbins = 10): ...
