from __future__ import annotations
from collections.abc import Mapping, Sequence
from decimal import Decimal
import importlib
import logging
import math
from numbers import Real
from pathlib import Path
import re
from typing import Any, Literal
import numpy as np
import pandas as pd
_DEFAULT_QUANTILES: object
_NUMERIC_ODPS_TYPES: object
_TABLE_NAME_RE: object
def _create_default_runner(): ...
def _normalize_name_list(value: str | Sequence[str] | None, parameter: str) -> list[str]: ...
def _validate_table_name(table_name: str, parameter: str) -> str: ...
def _quoted_table(table_name: str) -> str: ...
def _quoted_column(column_name: str) -> str: ...
def _base_odps_type(column: Any) -> str: ...
def _schema_columns(schema: Any) -> tuple[list[Any], list[Any]]: ...
def _resolve_columns(schema: Any, select_cols: str | Sequence[str] | None, skip_cols: str | Sequence[str] | None, group: str | Sequence[str] | None) -> tuple[list[str], list[str], dict[str, Any]]: ...
def _normalize_quantiles(q: Sequence[float] | None) -> tuple[list[float], list[str]]: ...
def _normalize_special_values(value: Any) -> list[Any]: ...
def _resolve_special_values(spec_missing_value: Any, features: list[str], schema_by_lower: Mapping[str, Any]) -> dict[str, list[Any]]: ...
def _sql_number(value: Any) -> str: ...
def _valid_numeric_expression(feature: str, special_values: Sequence[Any]) -> str: ...
def _build_batch_sql(input_table_name: str, features: list[str], group_cols: list[str], quantiles: list[float], quantile_method: str, percentile_accuracy: int, where_clause: str | None, include_missing_group: bool, special_values: Mapping[str, Sequence[Any]]) -> str: ...
def _result_column_lookup(frame: pd.DataFrame) -> dict[str, Any]: ...
def _reshape_batch_result(raw: pd.DataFrame, features: list[str], group_cols: list[str], quantile_labels: list[str]) -> pd.DataFrame: ...
def _sort_result(result: pd.DataFrame, features: list[str], group_cols: list[str]) -> pd.DataFrame: ...
def _schema_signature(schema: Any) -> list[tuple[str, str]]: ...
def _dataframe_schema(sqlrunner: Any, data: pd.DataFrame): ...
def _tables_may_match(left: str, right: str) -> bool: ...
def _write_odps_output(sqlrunner: Any, result: pd.DataFrame, output_table_name: str, output_table_mode: str) -> None: ...
def proc_means_odps(input_table_name: str, skip_cols: list[str] | None = None, select_cols: list[str] | None = None, batch_size: int = 50, group: str | list[str] | None = None, *, q: list[float] | None = None, quantile_method: Literal['approx', 'exact'] = 'approx', percentile_accuracy: int = 10000, where_clause: str | None = None, spec_missing_value: Any | list[Any] | dict[str, Any] | None = None, include_missing_group: bool = False, sqlrunner: Any | None = None, output_csv: str | Path | None = None, output_table_name: str | None = None, output_table_mode: Literal['overwrite', 'append'] | None = None) -> pd.DataFrame: ...
