# =============================================================================
# Modeling_Tool.Feature.PSI_Tool
# -----------------------------------------------------------------------------
# Copyright (c) 2026 Kyle Sun <github.com/Kyle-J-Sun>. All rights reserved.
# SuperModelingFactory — Licensed under the Business Source License 1.1.
#
# This stub describes the public API of a closed-source module compiled to a
# native extension (.so / .pyd). The original source is not distributed.
# Production / commercial use requires a separate commercial license.
#
# FINGERPRINT: SMF-PSITOOL-5299b9cc
#   (Unique trace marker. Do not remove or alter — used for plagiarism
#    detection across the public internet.)
# =============================================================================

import warnings
import numpy as np
import pandas as pd
from typing import Union, List, Dict, Optional, Tuple, Callable, Any
from tqdm import tqdm
from Modeling_Tool.Core.Binning_Tool import quick_binning
_MISSING_BIN: object
_PSI_BUCKET_POLICIES: object
def _validate_psi_bucket_policy(policy: str, caller: str) -> None: ...
def _psi_distributions_from_counts(expected_count: pd.Series, actual_count: pd.Series, expected_total: float, actual_total: float, *, content: float, policy: str) -> tuple[pd.Series, pd.Series, pd.Series, pd.Series]: ...

class PSICalculator:
    def __init__(self, buckets: int = 10, equal_freq: bool = True, min_bin_prop: float = 0.05, content: float = 1e-06, precision: int = 5, missing_policy: str = 'include', psi_missing_bucket_policy: str = 'smooth_laplace', feature_block_size: int | None = 64): ...
    def calculate(self, expected_df: pd.DataFrame, current_data: pd.DataFrame, varlist: List[str], group_by: Optional[str] = None, group_name: Optional[str] = None, return_details = False, missing_policy: Optional[str] = None, psi_missing_bucket_policy: Optional[str] = None) -> pd.DataFrame: ...

def _calculate_single_psi(expected_series: pd.Series, actual_series: pd.Series, buckets: int = 10, equal_freq: bool = True, return_details: bool = False, min_bin_prop: float = 0.05, content: float = 1e-06, precision: int = 5, missing_policy: str = 'include', psi_missing_bucket_policy: str = 'smooth_laplace') -> Union[float, Tuple[float, pd.DataFrame]]: ...
def calculate_psi(expected: Union[pd.DataFrame, pd.Series], actual: Union[pd.DataFrame, pd.Series], target_col: str, buckets: int = 10, equal_freq: bool = True, group_by: Optional[Union[str, List[str]]] = None, return_details: bool = False, min_bin_prop: float = 0.05, content: float = 1e-06, precision: int = 5, missing_policy: str = 'include', psi_missing_bucket_policy: str = 'smooth_laplace') -> Union[float, pd.DataFrame, Tuple[Dict, Dict]]: ...
def calculate_within_psi(data: pd.DataFrame, grp_name: str, target_col: str, benchmark: Optional[Any] = None, equal_freq: bool = True, buckets: int = 10, return_details: bool = False, min_bin_prop: float = 0.05, content: float = 1e-06, precision: int = 5, benchmark_display_name: Optional[str] = None, missing_policy: str = 'include', psi_missing_bucket_policy: str = 'smooth_laplace') -> Union[pd.DataFrame, Dict]: ...
def calculate_psi_within_dataset(data: pd.DataFrame, grp_name: str, varlist: List[str], benchmark: Optional[Any] = None, equal_freq: bool = True, buckets: int = 10, min_bin_prop: float = 0.05, content: float = 1e-06, precision: int = 5, missing_policy: str = 'include', psi_missing_bucket_policy: str = 'smooth_laplace') -> pd.DataFrame: ...
def calculate_multivar_psi_two_sets(expected_df: pd.DataFrame, actual_df: pd.DataFrame, varlist: List[str], group_by: Optional[Union[str, List[str]]] = None, buckets: int = 10, equal_freq: bool = True, min_bin_prop: float = 0.05, content: float = 1e-06, precision: int = 5, missing_policy: str = 'include', psi_missing_bucket_policy: str = 'smooth_laplace') -> pd.DataFrame: ...
def _coerce_psi_detail_frame(detail_obj, group_by: Optional[Union[str, List[str]]] = None) -> Optional[pd.DataFrame]: ...
def calculate_multigroup_psi_two_sets(expected_df: pd.DataFrame, actual_df: pd.DataFrame, varlist: List[str], group_by: Optional[Union[str, List[str]]] = None, buckets: int = 10, equal_freq: bool = True, min_bin_prop: float = 0.05, content: float = 1e-06, precision: int = 5, group_name: Optional[str] = None, return_details: bool = False, missing_policy: str = 'include', psi_missing_bucket_policy: str = 'smooth_laplace') -> Union[pd.DataFrame, Dict[str, pd.DataFrame]]: ...
def _calculate_grouped_psi_fixed_reference(expected_df: pd.DataFrame, actual_df: pd.DataFrame, varlist: List[str], group_name: str, buckets: int, equal_freq: bool, min_bin_prop: float, content: float, precision: int, return_details: bool, missing_policy: str, psi_missing_bucket_policy: str) -> Union[pd.DataFrame, Dict[str, pd.DataFrame]]: ...
