# =============================================================================
# Modeling_Tool.Core.Binning_Tool
# -----------------------------------------------------------------------------
# Copyright (c) 2026 Kyle Sun <github.com/Kyle-J-Sun>. All rights reserved.
# SuperModelingFactory — Licensed under the Business Source License 1.1.
#
# This stub describes the public API of a closed-source module compiled to a
# native extension (.so / .pyd). The original source is not distributed.
# Production / commercial use requires a separate commercial license.
#
# FINGERPRINT: SMF-BINNINGTOOL-c62e0857
#   (Unique trace marker. Do not remove or alter — used for plagiarism
#    detection across the public internet.)
# =============================================================================

import logging
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency, chi2
def get_max_nbins(data, nbins, min_bin_prop = 0.05): ...
def get_decision_tree_binning_edges(feature, target, max_leaf_nodes = 5, min_samples_leaf = 0.05, random_state = 42, missing_ref_value = None, spec_values = []): ...

class NumVarBinning:
    def __init__(self, var_name, spec_values = None, spec_digit = 3): ...
    def calc_equi_cutpoints(self, df, bins = 10, equi_method = 'equif'): ...
    def modify_cutpoints(self, df, points): ...
    def apt_binning(self, df, points, modify = True): ...
    def equi_binning(self, df, bins = 10, equi_method = 'equif'): ...
    def apply_binning(self, df): ...
    def auto_binning(self, df, tgt_name, max_bins = 10, min_prop_in_bin = 0.05, equi_bins = 200, equi_method = 'equif', init_points = None, binning_criteria = 'chi2', chi2_p = 0.95): ...
def cre_pvt(df, var_name, tgt_name): ...
def merge_bins(df_pvt, ilocs): ...
def observed_laplace(observed, digit = 6): ...
def cat_2_list(bin_series): ...
def get_bin_range(edges, precision = 5, ascending = False, left_sign = '(', right_sign = ']'): ...
def get_bin_range_list(data, col = '_bin_range'): ...
def chi2_auto_binning(df_pvt, max_bins, min_cnt_in_bin, p = 0.95): ...
def quick_binning(data, column, labels = None, nbins = 10, precision = 5, equal_freq = True, right = True, include_lowest = False, min_bin_prop = 0.05, ascending = True, include_missing = False, tree_binning = False, target = None, random_state = 42, fillna = -999999, spec_values = []): ...

class Binning:
    def __init__(self, data, column, tgt_name = None, nbins = 10, precision = 5, min_bin_prop = 0.05, include_missing = True, equal_freq = True, bin_colnames = ('_bin_num', '_bin_range'), ascending = True, right = True, include_lowest = False, tree_binning = False, chi2_method = False, chi2_p = 0.95, init_equi_bins = 200, fillna = -999999, spec_values = [], random_state = 42): ...
    def run_quick_binning(self): ...
    def run_chi2_binning(self, init_points = None): ...
    def run(self): ...
    def get_result(self, return_edges = True): ...
def chi2_binning(data, column, nbins = 10, precision = 5, min_bin_prop = 0.05, tgt_name = None, include_missing = True, equal_freq = True, bin_colnames = ('_bin_num', '_bin_range'), ascending = True, chi2_p = 0.95, init_equi_bins = 100, fillna = -999999, spec_values = [], init_points = None): ...
def run_binning(data, column, nbins = 10, precision = 5, min_bin_prop = 0.05, include_missing = True, equal_freq = True, bin_colnames = ('bin_num', 'bin_range'), ascending = False, right = True, include_lowest = False, tree_binning = False, target = None, random_state = 42, spec_values = []): ...
def super_binning(data, score, dep, nbins = 10, precision = 5, min_bin_prop = 0.05, include_missing = True, equal_freq = True, chi2_method = False, chi2_p = 0.95, init_equi_bins = 2000, fillna = -999999, spec_values = [], tree_binning = False, random_state = 42, return_edges = False, ascending = True, bin_colnames = ('_bin_num', '_bin_range')): ...
