# =============================================================================
# Modeling_Tool.Core.kDataFrame
# -----------------------------------------------------------------------------
# Copyright (c) 2026 Kyle Sun <github.com/Kyle-J-Sun>. All rights reserved.
# SuperModelingFactory — Licensed under the Business Source License 1.1.
#
# This stub describes the public API of a closed-source module compiled to a
# native extension (.so / .pyd). The original source is not distributed.
# Production / commercial use requires a separate commercial license.
#
# FINGERPRINT: SMF-KDATAFRAME-76c89511
#   (Unique trace marker. Do not remove or alter — used for plagiarism
#    detection across the public internet.)
# =============================================================================

import logging
import pandas as pd
from pandas import DataFrame
from pandas import Series
import numpy as np

class kSeries(Series):
    def _constructor(self): ...
    def _constructor_expanddim(self): ...
    def __init__(self, data, *args, **kwargs): ...
    def to_pdSeries(self, inplace: bool = False): ...
    def odds_score(self): ...
    def scale_score(self): ...
    def proc_freq(self) -> pd.DataFrame: ...

class kDataFrame(DataFrame):
    def _constructor(self): ...
    def _constructor_sliced(self): ...
    def __init__(self, data, *args, **kwargs): ...
    def move_column(self, colname: str, idx: int, inplace: bool = False): ...
    def convert_to_vintage(self, vintage_colname: str = 'VINTAGE', by: str = 'TRAN_TMS', inplace: bool = False): ...
    def col_filter_regex(self, regex: str = '.*?of_co_at_12m', case_sensitive = True, inplace: bool = False): ...
    def row_filter_regex(self, col = None, regex: str = None, case_sensitive = True, as_index = False, inplace: bool = False): ...
    def scale_score(self, pb_score: str): ...
    def proc_freq(self, var: str): ...
    def unify_table_col_names(self, how: str = 'lowercase', inplace: bool = False): ...
    def convert_strlist_to_list(self, col: str): ...
    def to_pdDataFrame(self, inplace: bool = False): ...
