# =============================================================================
# Modeling_Tool.WOE.WOE_Monotone_Binner
# -----------------------------------------------------------------------------
# Copyright (c) 2026 Kyle Sun <github.com/Kyle-J-Sun>. All rights reserved.
# SuperModelingFactory — Licensed under the Business Source License 1.1.
#
# This stub describes the public API of a closed-source module compiled to a
# native extension (.so / .pyd). The original source is not distributed.
# Production / commercial use requires a separate commercial license.
#
# FINGERPRINT: SMF-WOEMONOTONEB-b02e5879
#   (Unique trace marker. Do not remove or alter — used for plagiarism
#    detection across the public internet.)
# =============================================================================

from __future__ import annotations
import logging
import io
import os
import math
import warnings
import textwrap
import tempfile
from typing import List, Optional, Dict, Any, Union
import copy
from concurrent.futures import ProcessPoolExecutor, as_completed
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
_SPECIAL_BIN_PREFIX: object
_CATE_GROUP_SEP: object

class MonotoneWOEBinner:
    def __init__(self, feature_cols: List[str], target_col: str, n_init_bins: int = 20, min_bin_size: float = 0.03, min_n_bins: int = 2, eps: float = 1e-06, missing_woe: float = 0.0, special_values: Optional[List] = None, cate_feats: Optional[List[str]] = None, bin_label_decimals: Optional[int] = None): ...
    def _split_special(self, df: pd.DataFrame, feat: str): ...
    def _cat_to_bin_map(vr: Dict) -> Dict: ...
    def _split_special_for_plot(self, df: pd.DataFrame, feat: str, vr: Dict): ...
    def _assign_normal_bins(self, sub: pd.DataFrame, feat: str, vr: Dict, fitted_edges: list) -> pd.Series: ...
    def _compute_woe_single_bin(self, sub: pd.DataFrame, total_bad: float, total_good: float) -> Dict[str, float]: ...
    def _compute_woe_table(self, df: pd.DataFrame, feat: str, edges: list) -> tuple: ...
    def _compute_sv_table(self, sv_groups: Dict, total_bad: float, total_good: float) -> pd.DataFrame: ...
    def _is_monotone(woe_values: np.ndarray) -> bool: ...
    def _chi2_merge_one(self, df_normal: pd.DataFrame, feat: str, edges: list, chi2_p: float, chi2_init_size: int) -> list: ...
    def _greedy_fit_one(self, df: pd.DataFrame, feat: str, chi2_binning: bool = False, chi2_p: float = 0.99, chi2_init_size: int = 1000) -> Dict[str, Any]: ...
    def _sort_categories(cats: list) -> list: ...
    def _categorical_fit_one(self, df: pd.DataFrame, feat: str) -> Dict[str, Any]: ...
    def fit(self, df: pd.DataFrame, chi2_binning: bool = False, chi2_p: float = 0.99, chi2_init_size: int = 1000, n_jobs: int = 1) -> 'MonotoneWOEBinner': ...
    def _check_fitted(self): ...
    def refine_chi2(self, df: pd.DataFrame, features: Optional[List[str]] = None, chi2_p: float = 0.99, chi2_init_size: int = 1000, n_jobs: int = 1) -> 'MonotoneWOEBinner': ...
    def _dtree_edges(df_normal: pd.DataFrame, feat: str, target_col: str, max_bins: int, min_samples_leaf) -> list: ...
    def _monotone_merge_edges(df_normal: pd.DataFrame, feat: str, target_col: str, edges: list, eps: float) -> list: ...
    def refine_dtree(self, df: pd.DataFrame, features: Optional[List[str]] = None, max_bins: int = 6, min_samples_leaf: float = 0.05, monotone: bool = True, n_jobs: int = 1) -> 'MonotoneWOEBinner': ...
    def _cluster_cate_one(self, vr: Dict, max_bins: int, min_bin_size: float, badrate_tol: Optional[float]) -> Optional[Dict[str, Any]]: ...
    def refine_cate(self, features: Optional[List[str]] = None, max_bins: int = 5, min_bin_size: float = 0.0, badrate_tol: Optional[float] = None) -> 'MonotoneWOEBinner': ...
    def _bin_label(edges: list, bin_idx: int, n_bins: int, decimals: Optional[int] = None) -> str: ...
    def get_final_bins(self) -> Dict[str, pd.DataFrame]: ...
    def get_bin_edges(self) -> Dict[str, List[float]]: ...
    def load_woe_bins(self, bins_dict: dict) -> 'MonotoneWOEBinner': ...
    def _make_bin_labels(edges: List[float], n_bins: int, decimals: Optional[int] = None) -> List[str]: ...
    def _reconstruct_edges(bin_labels: List[str]) -> List[float]: ...
    def _looks_like_interval(label: str) -> bool: ...
    def _infer_cat_value(label): ...
    def apply_woe(self, data: pd.DataFrame, suffix: str = '_woe', inplace: bool = False) -> pd.DataFrame: ...
    def export_woe_report(self, report_path: str) -> None: ...
    def _render_woe_chart(self, feat: str, normal_df: pd.DataFrame, sv_df: pd.DataFrame, vr: Dict, dpi: int = 120, figsize: tuple = (9, 4.5)) -> io.BytesIO: ...
    def plot_woe_graph(self, graph_path: str, group_name: Optional[str] = None, _df_for_group: Optional[pd.DataFrame] = None, dpi: int = 150, figsize: tuple = (9, 6), bar_mode: str = 'clustered') -> None: ...
    def _plot_feat_small_multiples(self, feat, normal_df, sv_df, n_normal, n_sv, n_total, x_normal, x_sv, x_all, group_name, _df_for_group, graph_path, dpi, figsize, GOOD_COLOR, BAD_COLOR, SV_GOOD, SV_BAD, SV_WOE): ...
    def iv_summary(self) -> pd.DataFrame: ...
    def __repr__(self) -> str: ...
