# =============================================================================
# Modeling_Tool.WOE.WOE_Tool
# -----------------------------------------------------------------------------
# Copyright (c) 2026 Kyle Sun <github.com/Kyle-J-Sun>. All rights reserved.
# SuperModelingFactory — Licensed under the Business Source License 1.1.
#
# This stub describes the public API of a closed-source module compiled to a
# native extension (.so / .pyd). The original source is not distributed.
# Production / commercial use requires a separate commercial license.
#
# FINGERPRINT: SMF-WOETOOL-e00cc2c4
#   (Unique trace marker. Do not remove or alter — used for plagiarism
#    detection across the public internet.)
# =============================================================================

import numpy as np
import pandas as pd
import logging
from Modeling_Tool.Core.Binning_Tool import run_binning, super_binning, get_bin_range_list
from Modeling_Tool.Core.Slope_Tool import calculate_slope_manual
from Modeling_Tool.Core.utils import calc_iv, calc_woe
def is_monotonic(data, column, direction = 'auto', strict = False, handle_nan = 'drop'): ...
def check_monotonicity(data, var): ...

class WOETransformer:
    def __init__(self, nbins = 10, precision = 5, min_bin_prop = 0.05, include_missing = False, equal_freq = True, fillna = -999999, chi2_config = None, tree_binning_seed = None, spec_values = None, drop_bin_info = True, ret_woe_table = True): ...
    def _get_woe_table(self, binning_res, var, dep): ...
    def transform_single(self, train_df, var, dep, oot_df = None, check_monotonicity_flag = False): ...
    def transform(self, train_df, varlist, dep, oot_df = None, check_monotonicity_flag = False): ...
def convert_single_var_woe(data, var, woe_mapping_table, missing_ref = None, ret_bin_no = False): ...

class WOEMappingTransformer:
    def __init__(self, woe_mapping_table, missing_ref = None, ret_bin_no = False, ret_category = False, rename_orig_var = False, suffix = ''): ...
    def transform_single(self, data, var): ...
    def transform(self, data, varlist): ...
def woe_transform_cdaml(data, varlist, woe_mapping_path, missing_ref = None, ret_bin_no = False, ret_category = False, rename_orig_var = False, suffix = ''): ...
def get_woe_table(data, var, dep, grp_name = None, nbins = 10, precision = 5, min_bin_prop = 0.05, include_missing = True, equal_freq = True, fillna = -999999, chi2_config = None, tree_binning_seed = None, spec_values = None): ...
def plot_monotonicity_check(data, column, title = None, include_missing = True): ...
def woe_transform(train_df, var, dep, nbins, oot_df = None, chi2_config = None, tree_binning_seed = None, precision = 5, min_bin_prop = 0.05, include_missing = False, equal_freq = True, ascending = True, fillna = -999999, spec_values = None, drop_bin_info = True, ret_woe_table = True, check_monotonicity = False): ...
def woe_transformation(train_df, varlist, dep, oot_df = None, nbins = 10, chi2_config = None, tree_binning_seed = None, precision = 5, min_bin_prop = 0.05, include_missing = False, equal_freq = True, fillna = -999999, spec_values = None, drop_bin_info = True, ret_woe_table = True): ...
def mapping_woe(data, varlist, woe_mapping_table, suffix = '_woe', drop_bin_info = True): ...
