# =============================================================================
# Modeling_Tool.WOE.WOE_Plot_Tool
# -----------------------------------------------------------------------------
# Copyright (c) 2026 Kyle Sun <github.com/Kyle-J-Sun>. All rights reserved.
# SuperModelingFactory — Licensed under the Business Source License 1.1.
#
# This stub describes the public API of a closed-source module compiled to a
# native extension (.so / .pyd). The original source is not distributed.
# Production / commercial use requires a separate commercial license.
#
# FINGERPRINT: SMF-WOEPLOTTOOL-9fc25265
#   (Unique trace marker. Do not remove or alter — used for plagiarism
#    detection across the public internet.)
# =============================================================================

from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import logging
import os
import shutil
from matplotlib.font_manager import FontProperties
from .WOE_Tool import calc_woe, calc_iv, mapping_woe
from Modeling_Tool.Core.utils import mkdir_if_not_exist
def plot_woe(woe_df, var_rename = None, to_show = True, save_dir = None, fig_name = 'var.png'): ...
def get_woe_table(binning_res, var, dep): ...
def get_mapped_woe_summary_single(data, var, ref_woe_table, tgt_name): ...
def get_mapped_woe_summary_grp(data, var, ref_woe_table, tgt_name, grp_name = None): ...
def get_mapped_woe_summary(data, ref_woe_table, tgt_name, varlist = None, grp_name = None): ...
def plot_woe_group(woe_grp_df, grp_name = None, var_rename = None, to_show = True, save_dir = None, fig_name = 'var_group.png'): ...
def align_bin_num(woe_table, grp_woe_df, grp_name): ...
def get_bivar_graph(data, varlist, sep, ref_woe_table, save_dir, group = None, woe_suffix = '_woe'): ...

class WOEPlotter:
    def __init__(self, var_rename = None, to_show = True, save_dir = None, fig_name = 'var.png', grp_name = None): ...
    def plot(self, woe_df, var_rename = None, to_show = None, save_dir = None, fig_name = None): ...
    def plot_group(self, woe_grp_df, grp_name = None, var_rename = None, to_show = None, save_dir = None, fig_name = None): ...

class WOEAnalyzer:
    def __init__(self, ref_woe_table = None, tgt_name = None): ...
    def get_woe_table(self, binning_res, var, dep = None): ...
    def get_mapped_woe_summary_single(self, data, var, ref_woe_table = None, tgt_name = None): ...
    def get_mapped_woe_summary_grp(self, data, var, ref_woe_table = None, tgt_name = None, grp_name = None): ...
    def get_mapped_woe_summary(self, data, ref_woe_table = None, tgt_name = None, varlist = None, grp_name = None): ...
    def align_bin_num(self, woe_table, grp_woe_df, grp_name): ...
    def get_bivar_graph(self, data, varlist, sep = None, ref_woe_table = None, save_dir = None, group = None, woe_suffix = '_woe'): ...
