from __future__ import annotations
from dataclasses import dataclass
import re
from typing import Any, Iterable, Optional
import numpy as np
import pandas as pd
_CANONICAL_COLUMNS: object
def _upper_columns(df: pd.DataFrame) -> pd.DataFrame: ...
def _first_existing(df: pd.DataFrame, names: Iterable[str]) -> Optional[str]: ...
_NUMERIC_BOUND_RE: object
_INF_MARKERS: object
def _parse_interval_bound(token: str, side: str) -> float: ...
def _parse_interval_bounds(label: Any) -> tuple[float, float]: ...
def _coerce_woe_frame(df: pd.DataFrame, var: Optional[str], engine: str) -> pd.DataFrame: ...

@dataclass
class WOEEngineAdapter:
    engine: Any
    engine_name: str
    woe_suffix: str = '_woe'
    def transform(self, data: pd.DataFrame, varlist: Optional[list[str]] = None, suffix: str = '_woe') -> pd.DataFrame: ...
    def assign_bins(self, data: pd.DataFrame, var: str) -> pd.Series: ...
    def assign_bins_frame(self, data: pd.DataFrame, varlist: list[str], feature_block_size: int | None = 64) -> pd.DataFrame: ...
    def get_woe_table(self, varlist: Optional[list[str]] = None) -> pd.DataFrame: ...
    def get_bin_edges(self, varlist: Optional[list[str]] = None) -> dict[str, list[float]]: ...
    def get_engine_name(self) -> str: ...

class WOEMasterAdapter(WOEEngineAdapter):
    def __init__(self, engine: Any, woe_suffix: str = '_woe'): ...
    def transform(self, data: pd.DataFrame, varlist: Optional[list[str]] = None, suffix: str = '_woe') -> pd.DataFrame: ...
    def get_woe_table(self, varlist: Optional[list[str]] = None) -> pd.DataFrame: ...

class MonotoneBinnerAdapter(WOEEngineAdapter):
    def __init__(self, engine: Any, woe_suffix: str = '_woe'): ...
    def transform(self, data: pd.DataFrame, varlist: Optional[list[str]] = None, suffix: Optional[str] = None) -> pd.DataFrame: ...
    def get_woe_table(self, varlist: Optional[list[str]] = None) -> pd.DataFrame: ...
    def get_bin_edges(self, varlist: Optional[list[str]] = None) -> dict[str, list[float]]: ...

def as_woe_engine(engine: Any, woe_suffix: Optional[str] = None) -> Optional[WOEEngineAdapter]: ...
