from __future__ import annotations
from typing import Any, Optional
import pandas as pd

class WOEEngineAdapter:
    engine: Any
    engine_name: str
    woe_suffix: str
    def transform(self, data: pd.DataFrame, varlist: Optional[list[str]] = None, suffix: str = '_woe') -> pd.DataFrame: ...
    def assign_bins(self, data: pd.DataFrame, var: str) -> pd.Series: ...
    def get_woe_table(self, varlist: Optional[list[str]] = None) -> pd.DataFrame: ...
    def get_bin_edges(self, varlist: Optional[list[str]] = None) -> dict[str, list[float]]: ...
    def get_engine_name(self) -> str: ...

class WOEMasterAdapter(WOEEngineAdapter):
    def __init__(self, engine: Any, woe_suffix: str = '_woe'): ...

class MonotoneBinnerAdapter(WOEEngineAdapter):
    def __init__(self, engine: Any, woe_suffix: str = '_woe'): ...

def as_woe_engine(engine: Any, woe_suffix: str = '_woe') -> Optional[WOEEngineAdapter]: ...
