# =============================================================================
# Modeling_Tool.WOE.WOE_Master
# -----------------------------------------------------------------------------
# Copyright (c) 2026 Kyle Sun <github.com/Kyle-J-Sun>. All rights reserved.
# SuperModelingFactory — Licensed under the Business Source License 1.1.
#
# This stub describes the public API of a closed-source module compiled to a
# native extension (.so / .pyd). The original source is not distributed.
# Production / commercial use requires a separate commercial license.
#
# FINGERPRINT: SMF-WOEMASTER-984661fa
#   (Unique trace marker. Do not remove or alter — used for plagiarism
#    detection across the public internet.)
# =============================================================================

import os
import pandas as pd
import numpy as np
from .WOE_Plot_Tool import get_bivar_graph
from .WOE_Tool import mapping_woe, woe_transform
from Modeling_Tool.Core.Binning_Tool import run_binning, get_bin_range_list
from Modeling_Tool.Core.utils import calc_woe, calc_iv
def get_overall_woe_table(woe_master, data, varlist = None): ...
def get_group_woe_table(woe_master, data, group, varlist = None): ...

class WOE_Master(object):
    def __init__(self, train_data, varlist, dep = None, graph_save_dir = '', woe_suffix = '_woe', missing_ref_value = -999999, remove_exist_dir = False): ...
    def remove_folder(file_path): ...
    def load_mapping_table(self, mapping_table_csv): ...
    def fit(self, nbins = 10, equal_freq = True, tree_binning_seed = None, chi2_config = None, precision = 5, min_bin_prop = 0.05, include_missing = True, fillna = None, spec_values = []): ...
    def get_mapping_table(self): ...
    def save_mapping_table(self, save_dir): ...
    def transform(self, data = None, varlist = None): ...
    def update_woe(self, varlist, nbins = 10, equal_freq = True, tree_binning_seed = None, chi2_config = None, precision = 5, min_bin_prop = 0.05, include_missing = True, fillna = None, spec_values = []): ...
    def plot_bivar_graph(self, data, group, dirname, varlist = None): ...
def load_mapping_table(mapping_table_csv): ...
def get_mapping_table(woe_dict): ...
def save_mapping_table(woe_dict, save_dir): ...
def transform(data, varlist, woe_mapping_table, woe_suffix = '_woe'): ...
def plot_bivar_graph_func(data, varlist, dep, ref_woe_table, group, save_dir): ...
