# =============================================================================
# Modeling_Tool.Model.Backward_Tool
# -----------------------------------------------------------------------------
# Copyright (c) 2026 Kyle Sun <github.com/Kyle-J-Sun>. All rights reserved.
# SuperModelingFactory — Licensed under the Business Source License 1.1.
#
# This stub describes the public API of a closed-source module compiled to a
# native extension (.so / .pyd). The original source is not distributed.
# Production / commercial use requires a separate commercial license.
#
# FINGERPRINT: SMF-BACKWARDTOOL-11b388c0
#   (Unique trace marker. Do not remove or alter — used for plagiarism
#    detection across the public internet.)
# =============================================================================

import os
import time
import logging
import numpy as np
import pandas as pd
from collections import OrderedDict
from .GBM_Tool import lgbm_quick_train, lgb_varimp, xgbm_quick_train, xgb_varimp
from Modeling_Tool.Core.utils import save_model, load_model
from Modeling_Tool.Eval.Model_Eval_Tool import get_perf_summary
def backward_lgbm(train_data, validation_data, x, y, varreduct_params, results_output_dir, varreduct_perf_filename, modelsave_dir, cat_x = None, wgt_col = None, test_data_dict = None, stopping_metric = 'AUC', seed = 12345, varreduct_modelid_prefix = 'varreduct_test0', varreduct_max_nmodels = 50, varreduct_minvar = 30, cum_varimp = 0.98, backward_continue_from_nmodel = 0, scrutiny_range = None, scrutiny_step = None): ...
def backward_xgbm(train_data, validation_data, x, y, varreduct_params, results_output_dir, varreduct_perf_filename, modelsave_dir, mc_dict = None, cat_x = None, wgt_col = None, test_data_dict = None, stopping_metric = 'AUC', seed = 12345, varreduct_modelid_prefix = 'varreduct_test0', varreduct_max_nmodels = 50, varreduct_minvar = 30, cum_varimp = 0.98, backward_continue_from_nmodel = 0, scrutiny_range = None, scrutiny_step = None): ...

class BackwardVariableEliminator:
    def __init__(self, model_type = None, train_data = None, validation_data = None, params = None, y = None, oot_data = None, wgt_col = None, cat_x = None, mc_dict = None, stopping_metric = 'AUC', seed = 12345, modelsave_dir = None, algorithm = 'lgb', results_output_dir = None, varreduct_perf_filename = 'perf.csv', varreduct_modelid_prefix = 'varreduct'): ...
    def _validate_train_params(self): ...
    def _validate_analyze_params(self): ...
    def _get_hyperparams_preset(self): ...
    def _merge_params(self): ...
    def fit(self, x, varreduct_max_nmodels = 50, varreduct_minvar = 30, cum_varimp = 0.98, backward_continue_from_nmodel = 0, scrutiny_range = None, scrutiny_step = None, test_data_dict = None): ...
    def get_backward_perf(self, overfitting_cut = [np.inf, np.inf]): ...
    def get_backward_summary(self, grp_name = None, subgroup_value = None, min_data_size = 10): ...
    def add_group(self, grp_name, subgroup_value = None): ...
    def set_overfitting_cut(self, auc_shift = np.inf, ks_shift = np.inf): ...
    def analyze(self, result_dir = None): ...
    def fit_and_analyze(self, x, results_output_dir = None, modelsave_dir = None, varreduct_perf_filename = 'perf.csv', varreduct_modelid_prefix = 'varreduct', varreduct_max_nmodels = 50, varreduct_minvar = 30, cum_varimp = 0.98, scrutiny_range = None, scrutiny_step = None): ...
    def switch_model(self, new_model_type): ...
    def get_result(self): ...

class BackwardEliminationAnalyzer(BackwardVariableEliminator):
    def __init__(self, ins_df = None, oos_df = None, oot_df = None, dep = None, dir_path = None, algorithm = 'xgb', min_data_size = 10): ...
