# =============================================================================
# Modeling_Tool.Model.GBM_Tool
# -----------------------------------------------------------------------------
# Copyright (c) 2026 Kyle Sun <github.com/Kyle-J-Sun>. All rights reserved.
# SuperModelingFactory — Licensed under the Business Source License 1.1.
#
# This stub describes the public API of a closed-source module compiled to a
# native extension (.so / .pyd). The original source is not distributed.
# Production / commercial use requires a separate commercial license.
#
# FINGERPRINT: SMF-GBMTOOL-3641af20
#   (Unique trace marker. Do not remove or alter — used for plagiarism
#    detection across the public internet.)
# =============================================================================

import pandas as pd
import numpy as np
from Modeling_Tool.Core.utils import load_model, save_model
from sklearn.calibration import CalibratedClassifierCV, calibration_curve
from sklearn.metrics import brier_score_loss, roc_auc_score
def _calibrated_classifier(estimator, method, cv): ...
def _get_lgb(): ...
def _get_xgb(): ...
def _get_catboost(): ...
def _coerce_feature_names(feature_names): ...
def _extract_estimator_feature_names(estimator): ...
def _ensure_feature_names_in(estimator, feature_names): ...
_CATBOOST_METRIC_ALIASES: object
def _normalize_catboost_params(params_dict): ...
def set_num_leaves(max_depth = 5, wgt = 1): ...
def lgb_model(x, y, valx, valy, params_dict, wgt = None, init_score = None, eval_sample_weight = None, eval_init_score = None): ...
def lgb_varimp(model): ...
def lgbm_quick_train(train_data, validation_data, x, y, params, wgt_col = None, val_wgt_col = None, cat_x_train = None): ...
def xgb_model(x, y, valx, valy, params_dict, sample_weight = None, sample_weight_eval_set = None, base_margin = None, eval_base_margin = None): ...
def xgb_varimp(model): ...
def xgbm_quick_train(train_data, validation_data, x, y, wgt_col = None, params = None, sample_weight_eval_set = None, val_wgt_col = None): ...
def catboost_model(x, y, valx, valy, params_dict, sample_weight = None): ...
def catboost_varimp(model): ...
def catboost_quick_train(train_data, validation_data, x, y, params, wgt_col = None, val_wgt_col = None, cat_features = None): ...

class LightGBMModel:
    def __init__(self, params, model = None): ...
    def fit(self, x, y, valx, valy, wgt = None, init_score = None, sample_weight = None, eval_sample_weight = None, eval_init_score = None): ...
    def predict(self, x): ...
    def get_feature_importance(self, importance_type = 'gain'): ...
    def save(self, path): ...
    def load(self, path): ...
    def calibrate(self, x, y, method = 'sigmoid', cv = 'prefit'): ...
    def calibration_curve(self, x, y, n_bins = 10): ...
    def brier_score(self, x, y): ...
    def roc_auc(self, x, y): ...

class XGBoostModel:
    def __init__(self, params, model = None): ...
    def fit(self, x, y, valx, valy, sample_weight = None, sample_weight_eval_set = None, base_margin = None, eval_base_margin = None): ...
    def predict(self, x): ...
    def get_feature_importance(self, importance_type = 'gain'): ...
    def save(self, path): ...
    def load(self, path): ...
    def calibrate(self, x, y, method = 'sigmoid', cv = 'prefit'): ...
    def calibration_curve(self, x, y, n_bins = 10): ...
    def brier_score(self, x, y): ...
    def roc_auc(self, x, y): ...

class CatBoostModel:
    def __init__(self, params, model = None): ...
    def fit(self, x, y, valx, valy, sample_weight = None): ...
    def predict(self, x): ...
    def get_feature_importance(self, importance_type = 'gain'): ...
    def save(self, path): ...
    def load(self, path): ...
    def calibrate(self, x, y, method = 'sigmoid', cv = 'prefit'): ...
    def calibration_curve(self, x, y, n_bins = 10): ...
    def brier_score(self, x, y): ...
    def roc_auc(self, x, y): ...

class GradientBoostingModel:
    def __init__(self, model_type, params): ...
    @staticmethod
    def _detect_model_type(estimator): ...
    @classmethod
    def from_fitted(cls, model, model_type = None, params = None): ...
    def __getattr__(self, name): ...
    def __getstate__(self): ...
    def __setstate__(self, state): ...
    @staticmethod
    def _sigmoid(z): ...
    def fit(self, x, y, valx, valy, init_score = None, sample_weight = None, eval_sample_weight = None, sample_weight_eval_set = None, eval_init_score = None, **kwargs): ...
    def get_base_margin(self, x): ...
    def predict_with_base_margin(self, x, base_margin, return_prob = True): ...
    def predict(self, x): ...
    def get_feature_importance(self, importance_type = 'gain'): ...
    def save(self, path): ...
    def load(self, path): ...
    def calibrate(self, x, y, method = 'sigmoid', cv = 'prefit'): ...
    def brier_score(self, x, y): ...
    def roc_auc(self, x, y): ...
