# =============================================================================
# Modeling_Tool.Model.GBM_Tool
# -----------------------------------------------------------------------------
# Copyright (c) 2026 Kyle Sun <github.com/Kyle-J-Sun>. All rights reserved.
# SuperModelingFactory — Licensed under the Business Source License 1.1.
#
# This stub describes the public API of a closed-source module compiled to a
# native extension (.so / .pyd). The original source is not distributed.
# Production / commercial use requires a separate commercial license.
#
# FINGERPRINT: SMF-GBMTOOL-3641af20
#   (Unique trace marker. Do not remove or alter — used for plagiarism
#    detection across the public internet.)
# =============================================================================

import pandas as pd
import lightgbm as lgb
import xgboost as xgb
from Modeling_Tool.Core.utils import load_model, save_model
from sklearn.calibration import CalibratedClassifierCV, calibration_curve
from sklearn.metrics import brier_score_loss, roc_auc_score
def set_num_leaves(max_depth = 5, wgt = 1): ...
def lgb_model(x, y, valx, valy, params_dict, wgt = None, init_score = None): ...
def lgb_varimp(model): ...
def lgbm_quick_train(train_data, validation_data, x, y, params, wgt_col = None, cat_x_train = None): ...
def xgb_model(x, y, valx, valy, params_dict, sample_weight = None, sample_weight_eval_set = None, base_margin = None): ...
def xgbm_quick_train(train_data, validation_data, x, y, wgt_col, params, cat_x_train = None, weight_eval_set = False): ...
def xgb_varimp(model): ...

class LightGBMModel:
    def __init__(self, params, model = None): ...
    def fit(self, x, y, valx, valy, wgt = None, init_score = None): ...
    def predict(self, x): ...
    def predict_proba(self, x): ...
    def get_feature_importance(self): ...
    def get_best_iteration(self): ...
    def get_learning_curve(self): ...
    def save_model(self, filepath): ...
    def load_model(self, filepath): ...

class XGBoostModel:
    def __init__(self, params, model = None): ...
    def fit(self, x, y, valx, valy, sample_weight = None, sample_weight_eval_set = None, base_margin = None): ...
    def predict(self, x): ...
    def predict_proba(self, x): ...
    def get_feature_importance(self): ...
    def get_best_iteration(self): ...
    def save_model(self, filepath): ...
    def load_model(self, filepath): ...
    def get_base_margin_from_model(model, X, objective = 'binary:logistic'): ...
    def predict_with_base_margin(old_model, new_model, X, objective = 'binary:logistic', return_prob = True): ...

class GradientBoostingModel:
    def __init__(self, model_type, params, model = None): ...
    def _init_model(self, model): ...
    def fit(self, x, y, valx, valy, init_score = None, **kwargs): ...
    def fit_calibrated_model(self, X_cal, y_cal, method = 'sigmoid', cv = 'prefit', **kwargs): ...
    def predict(self, x, calibrated_model = False): ...
    def predict_proba(self, x, calibrated_model = False): ...
    def get_feature_importance(self): ...
    def get_best_iteration(self): ...
    def save_model(self, filepath): ...
    def load_model(self, filepath): ...
    def switch_model(self, new_model_type): ...
