# =============================================================================
# Modeling_Tool.Model.LRM_Tool
# -----------------------------------------------------------------------------
# Copyright (c) 2026 Kyle Sun <github.com/Kyle-J-Sun>. All rights reserved.
# SuperModelingFactory — Licensed under the Business Source License 1.1.
#
# This stub describes the public API of a closed-source module compiled to a
# native extension (.so / .pyd). The original source is not distributed.
# Production / commercial use requires a separate commercial license.
#
# FINGERPRINT: SMF-LRMTOOL-3703d3ce
#   (Unique trace marker. Do not remove or alter — used for plagiarism
#    detection across the public internet.)
# =============================================================================

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
import logging
from Modeling_Tool.Core.sample_weight_utils import resolve_sample_weight
from Modeling_Tool._utils.nan_guard import warn_if_nan_ratio_exceeds
def _sanitize_lr_params(params): ...
def _patch_calibrated_model(cal_model): ...
def lr_model(mdlx, mdly, valx, valy, params_dict, sample_weight = None): ...
def lr_varimp(model): ...
def _predict_positive_proba(model, x_arr): ...
def fast_lr_pvalues(model, x, feature_names): ...
def get_lr_statsmodel_summary(model, x, y, feature_names = None): ...
def _compute_log_likelihood(model, x, y, sample_weight = None): ...
def compute_aic(model, x, y, sample_weight = None): ...
def compute_bic(model, x, y, sample_weight = None): ...
def _prepare_nan_handled_frame(data, nan_handling = 'fillna_median', warn_threshold = 0.05, context = ''): ...

class FeatureSelectionAnalyzer:
    def __init__(self, significance_level = 0.05): ...
    def chi2_selection(self, data, feature_cols, target_col, nan_handling = 'fillna_median', nan_warn_threshold = 0.05): ...
    def compute_vif(self, data, nan_handling = 'fillna_median', nan_warn_threshold = 0.05, sample_weight = None): ...
    def correlation_filter(self, data, threshold = 0.8): ...

class LRMaster:
    def __init__(self, params = None, model = None, varlist = None, tgt_name = None, standardize = False, scaler = None): ...
    def _make_scaler(self): ...
    def _fit_standardizer(self, x): ...
    def _apply_standardizer(self, x): ...
    def set_data(self, data): ...
    def __getstate__(self): ...
    def __setstate__(self, state): ...
    def _require_data(self, data): ...
    def fit(self, data, varlist, tgt_name, val_data = None, val_varlist = None, val_tgt_name = None, weight_col = None): ...
    def calibrate_model(self, model = None, train_df = None, method = 'sigmoid', cv = 5, weight_col = None, sample_weight = None): ...
    def eval_calibrated_outcome(self, evalset, plot = False, weight_col = None, sample_weight = None): ...
    def predict(self, data, varlist = None, calibrated_model = False): ...
    def predict_proba(self, data, varlist = None, calibrated_model = False): ...
    def get_variable_importance(self): ...
    def get_statsmodel_summary(self, data = None, varlist = None, tgt_name = None): ...
    def get_aic(self, data = None, varlist = None, tgt_name = None, weight_col = None): ...
    def get_bic(self, data = None, varlist = None, tgt_name = None, weight_col = None): ...
    def stepwise_selection(self, data, varlist, tgt_name, criterion = 'aic', direction = 'both', max_iter = 100, verbose = True, weight_col = None): ...
    def grid_search_params(self, data, varlist, tgt_name, eval_sets, param_grid, objective = 'oot_gap_penalized', primary_set = None, gap_ref_sets = None, metric = 'auc', refit = True, verbose = True, weight_col = None, eval_weight_col = None): ...
    def clone(self): ...
