# =============================================================================
# Modeling_Tool.Model.LRM_Tool
# -----------------------------------------------------------------------------
# Copyright (c) 2026 Kyle Sun <github.com/Kyle-J-Sun>. All rights reserved.
# SuperModelingFactory — Licensed under the Business Source License 1.1.
#
# This stub describes the public API of a closed-source module compiled to a
# native extension (.so / .pyd). The original source is not distributed.
# Production / commercial use requires a separate commercial license.
#
# FINGERPRINT: SMF-LRMTOOL-3703d3ce
#   (Unique trace marker. Do not remove or alter — used for plagiarism
#    detection across the public internet.)
# =============================================================================

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
import logging
def lr_model(mdlx, mdly, valx, valy, params_dict): ...
def lr_varimp(model): ...
def get_lr_statsmodel_summary(df, x_col, y_col, verbose = True): ...
def get_lr_sklearn_model_summary(df, tgt_name, model, verbose = False, varlist = None): ...
def visualise_pvalue(sklearn_stats_df): ...
def calculate_aic_bic(model, X, y): ...
def calculate_feature_importance(model, X, y, feature_names = None): ...
def get_lr_varimp_summary(data, lr_model, varlist, tgt_name): ...
def reorder_by_correlation(varlist, data, threshold = 0.7, method = 'descending'): ...
def lr_stepwise_var_selection(ins_df, oos_df, oot_df, dep, candidate_varlist, params = None, model_input = None, standardize = False, method = 'backward', model = None, cumulative = False, train_benchmark_model = False, order_permutations = None, random_state = 42, corr_threshold = None): ...

class LRMaster:
    def __init__(self, params = None, model = None, varlist = None, tgt_name = None): ...
    def standardize(self, data = None, varlist = None): ...
    def standardize_transform(self, data): ...
    def fit(self, data, varlist, tgt_name, val_data = None, val_varlist = None, val_tgt_name = None): ...
    def calibrate_model(self, model = None, train_df = None, method = 'sigmoid', cv = 5): ...
    def eval_calibrated_outcome(self, evalset, plot = False): ...
    def predict(self, data, varlist = None, calibrated_model = False): ...
    def predict_proba(self, data, varlist = None, calibrated_model = False): ...
    def get_variable_importance(self): ...
    def get_model_summary(self, data = None, verbose = False): ...
    def get_feature_importance(self, data = None): ...
    def get_aic_bic(self, data = None): ...
    def get_comprehensive_varimp_summary(self, data = None): ...
    def stepwise_selection(self, ins_df, oos_df, oot_df, candidate_varlist, dep = None, model = None, params = None, model_input = None, method = 'backward', cumulative = False, standardize = False, train_benchmark_model = False, order_permutations = None, random_state = 42, corr_threshold = None): ...
    def grid_search_params(self, data, varlist, tgt_name, eval_sets, param_grid, objective = 'oot_gap_penalized', primary_set = None, gap_ref_sets = None, metric = 'auc', refit = True, verbose = True): ...
    def visualize_pvalues(self, data = None): ...

class FeatureSelectionAnalyzer:
    def __init__(self, ins_df, oos_df, oot_df, dep, params = None, standardize = False): ...
    def _train_and_evaluate(self, features): ...
    def analyze_high_corr_group(self, base_features, group_features): ...
    def analyze_independent_gain_and_order(self, base_features, candidate_features): ...
