from typing import Any

class GainsTableCalculator:
    def __init__(self, data: Any = ..., dep: Any = ..., score: Any = ..., nbins: int = ..., weight_col: Any = ..., weighted_binning: Any = ..., **kwargs: Any) -> None: ...
    def calculate(self, weight_col: Any = ..., **kwargs: Any) -> Any: ...

class PerformanceEvaluator:
    def __init__(self, tgt_name: Any = ..., scr_name: Any = ..., weight_col: Any = ..., nbins: int = ..., **kwargs: Any) -> None: ...
    def add_dataset(self, name: Any, data: Any, weight_col: Any = ..., **kwargs: Any) -> Any: ...
    def evaluate(self, weight_col: Any = ..., to_show: bool = ..., display: bool = ..., **kwargs: Any) -> Any: ...

class Model_Evaluation_Tool:
    def __init__(self, data: Any = ..., tgt_name: Any = ..., scr_name: Any = ..., weight_col: Any = ..., **kwargs: Any) -> None: ...
    def model_perf_compare(self, train: Any = ..., validation: Any = ..., oot: Any = ..., weight_col: Any = ..., **kwargs: Any) -> Any: ...
    def get_gains_summary(self, data: Any = ..., weight_col: Any = ..., **kwargs: Any) -> Any: ...
    def get_cust_metric_summary(self, data: Any = ..., weight_col: Any = ..., **kwargs: Any) -> Any: ...
    def get_cross_risk_summary(self, data: Any = ..., weight_col: Any = ..., **kwargs: Any) -> Any: ...
    def cross_perf_eval(self, **kwargs: Any) -> Any: ...

def calc_roc(y_true: Any, y_score: Any, sample_weight: Any = ...) -> Any: ...
def calc_pr(y_true: Any, y_score: Any, sample_weight: Any = ...) -> Any: ...
def get_gains_table(data: Any, dep: Any, score: Any, nbins: int = ..., weight_col: Any = ..., weighted_binning: Any = ..., **kwargs: Any) -> Any: ...
def get_perf_summary(train: Any = ..., validation: Any = ..., oot: Any = ..., tgt_name: Any = ..., scr_name: Any = ..., weight_col: Any = ..., nbins: int = ..., to_show: bool = ..., display: bool = ..., **kwargs: Any) -> Any: ...
def calc_lift_apt(y_true: Any, y_score: Any, start: float = ..., stop: float = ..., step: float = ..., sample_weight: Any = ...) -> Any: ...
def calc_equid_dist(y_true: Any, y_score: Any, bins: int = ..., sample_weight: Any = ..., **kwargs: Any) -> Any: ...
def calc_equid_pct(y_true: Any, y_score: Any, bins: int = ..., sample_weight: Any = ..., **kwargs: Any) -> Any: ...
def calc_fixed_pct(y_true: Any, y_score: Any, sample_weight: Any = ..., **kwargs: Any) -> Any: ...
def evaluate_performance(datasets: Any = ..., tgt_name: Any = ..., scr_name: Any = ..., sample_weight: Any = ..., **kwargs: Any) -> Any: ...
def comparison_performance(*args: Any, sample_weight: Any = ..., **kwargs: Any) -> Any: ...
def cross_risk(data: Any, row_var: Any = ..., col_var: Any = ..., tgt_name: Any = ..., weight_col: Any = ..., **kwargs: Any) -> Any: ...
def get_gains_table_by_cust_metrics(data: Any, dep: Any, score: Any, cust_metrics: Any = ..., weight_col: Any = ..., nbins: int = ..., **kwargs: Any) -> Any: ...
def lgbm_quick_train(train_data: Any, validation_data: Any = ..., x: Any = ..., y: Any = ..., params: Any = ..., wgt_col: Any = ..., val_wgt_col: Any = ..., **kwargs: Any) -> Any: ...
def xgbm_quick_train(train_data: Any, validation_data: Any = ..., x: Any = ..., y: Any = ..., params: Any = ..., wgt_col: Any = ..., val_wgt_col: Any = ..., sample_weight_eval_set: Any = ..., **kwargs: Any) -> Any: ...
def catboost_quick_train(train_data: Any, validation_data: Any = ..., x: Any = ..., y: Any = ..., params: Any = ..., wgt_col: Any = ..., val_wgt_col: Any = ..., **kwargs: Any) -> Any: ...
def backward_lgbm(train_data: Any, varlist: Any, dep: Any, varreduct_params: Any = ..., stopping_metric: str = ..., seed: int = ..., num_boost_round: int = ..., early_stopping_rounds: int = ..., importance_type: str = ..., cum_importance_threshold: float = ..., min_vars: int = ..., validation_data: Any = ..., test_data_dict: Any = ..., ret_perf: bool = ..., weight_col: Any = ..., validation_weight_col: Any = ..., wgt_col: Any = ..., **kwargs: Any) -> Any: ...
def backward_xgbm(train_data: Any, varlist: Any, dep: Any, varreduct_params: Any = ..., stopping_metric: str = ..., seed: int = ..., num_boost_round: int = ..., early_stopping_rounds: int = ..., importance_type: str = ..., cum_importance_threshold: float = ..., min_vars: int = ..., validation_data: Any = ..., test_data_dict: Any = ..., ret_perf: bool = ..., weight_col: Any = ..., validation_weight_col: Any = ..., wgt_col: Any = ..., **kwargs: Any) -> Any: ...
def apply_eval_patches(ns: Any = ...) -> None: ...
def apply_model_patches(ns: Any = ...) -> None: ...
